/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Demux1a2_dest.v:1" *)
module demux1a2dest_est(datain_dest, reset_L, clk, class, dest, outdest0, outdest1);
  (* src = "Demux1a2_dest.v:31" *)
  wire [7:0] _000_;
  (* src = "Demux1a2_dest.v:31" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "Demux1a2_dest.v:6" *)
  input class;
  (* src = "Demux1a2_dest.v:5" *)
  input clk;
  (* src = "Demux1a2_dest.v:12" *)
  wire [7:0] data_reg0dest;
  (* src = "Demux1a2_dest.v:12" *)
  wire [7:0] data_reg1dest;
  (* src = "Demux1a2_dest.v:3" *)
  input [7:0] datain_dest;
  (* src = "Demux1a2_dest.v:7" *)
  input dest;
  (* src = "Demux1a2_dest.v:9" *)
  output [7:0] outdest0;
  (* src = "Demux1a2_dest.v:10" *)
  output [7:0] outdest1;
  (* src = "Demux1a2_dest.v:4" *)
  input reset_L;
  NOR _068_ (
    .A(data_reg1dest[7]),
    .B(dest),
    .Y(_033_)
  );
  NOT _069_ (
    .A(datain_dest[7]),
    .Y(_034_)
  );
  NAND _070_ (
    .A(_034_),
    .B(dest),
    .Y(_035_)
  );
  NAND _071_ (
    .A(_035_),
    .B(reset_L),
    .Y(_036_)
  );
  NOR _072_ (
    .A(_036_),
    .B(_033_),
    .Y(outdest1[7])
  );
  NOT _073_ (
    .A(reset_L),
    .Y(_037_)
  );
  NOT _074_ (
    .A(dest),
    .Y(_038_)
  );
  NOT _075_ (
    .A(data_reg0dest[0]),
    .Y(_039_)
  );
  NOR _076_ (
    .A(_039_),
    .B(_038_),
    .Y(_040_)
  );
  NOT _077_ (
    .A(datain_dest[0]),
    .Y(_041_)
  );
  NOR _078_ (
    .A(dest),
    .B(_041_),
    .Y(_042_)
  );
  NOR _079_ (
    .A(_042_),
    .B(_040_),
    .Y(_043_)
  );
  NOR _080_ (
    .A(_043_),
    .B(_037_),
    .Y(outdest0[0])
  );
  NOT _081_ (
    .A(data_reg0dest[1]),
    .Y(_044_)
  );
  NOR _082_ (
    .A(_044_),
    .B(_038_),
    .Y(_045_)
  );
  NOT _083_ (
    .A(datain_dest[1]),
    .Y(_046_)
  );
  NOR _084_ (
    .A(_046_),
    .B(dest),
    .Y(_047_)
  );
  NOR _085_ (
    .A(_047_),
    .B(_045_),
    .Y(_048_)
  );
  NOR _086_ (
    .A(_048_),
    .B(_037_),
    .Y(outdest0[1])
  );
  NOT _087_ (
    .A(data_reg0dest[2]),
    .Y(_049_)
  );
  NOR _088_ (
    .A(_049_),
    .B(_038_),
    .Y(_050_)
  );
  NOT _089_ (
    .A(datain_dest[2]),
    .Y(_051_)
  );
  NOR _090_ (
    .A(_051_),
    .B(dest),
    .Y(_052_)
  );
  NOR _091_ (
    .A(_052_),
    .B(_050_),
    .Y(_053_)
  );
  NOR _092_ (
    .A(_053_),
    .B(_037_),
    .Y(outdest0[2])
  );
  NOT _093_ (
    .A(data_reg0dest[3]),
    .Y(_054_)
  );
  NOR _094_ (
    .A(_054_),
    .B(_038_),
    .Y(_055_)
  );
  NOT _095_ (
    .A(datain_dest[3]),
    .Y(_056_)
  );
  NOR _096_ (
    .A(_056_),
    .B(dest),
    .Y(_057_)
  );
  NOR _097_ (
    .A(_057_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _098_ (
    .A(_058_),
    .B(_037_),
    .Y(outdest0[3])
  );
  NOT _099_ (
    .A(data_reg0dest[4]),
    .Y(_059_)
  );
  NOR _100_ (
    .A(_059_),
    .B(_038_),
    .Y(_060_)
  );
  NOT _101_ (
    .A(datain_dest[4]),
    .Y(_061_)
  );
  NOR _102_ (
    .A(_061_),
    .B(dest),
    .Y(_062_)
  );
  NOR _103_ (
    .A(_062_),
    .B(_060_),
    .Y(_063_)
  );
  NOR _104_ (
    .A(_063_),
    .B(_037_),
    .Y(outdest0[4])
  );
  NOT _105_ (
    .A(data_reg0dest[5]),
    .Y(_064_)
  );
  NOR _106_ (
    .A(_064_),
    .B(_038_),
    .Y(_065_)
  );
  NOT _107_ (
    .A(datain_dest[5]),
    .Y(_066_)
  );
  NOR _108_ (
    .A(_066_),
    .B(dest),
    .Y(_067_)
  );
  NOR _109_ (
    .A(_067_),
    .B(_065_),
    .Y(_002_)
  );
  NOR _110_ (
    .A(_002_),
    .B(_037_),
    .Y(outdest0[5])
  );
  NOT _111_ (
    .A(data_reg0dest[6]),
    .Y(_003_)
  );
  NOR _112_ (
    .A(_003_),
    .B(_038_),
    .Y(_004_)
  );
  NOT _113_ (
    .A(datain_dest[6]),
    .Y(_005_)
  );
  NOR _114_ (
    .A(_005_),
    .B(dest),
    .Y(_006_)
  );
  NOR _115_ (
    .A(_006_),
    .B(_004_),
    .Y(_007_)
  );
  NOR _116_ (
    .A(_007_),
    .B(_037_),
    .Y(outdest0[6])
  );
  NOT _117_ (
    .A(data_reg0dest[7]),
    .Y(_008_)
  );
  NOR _118_ (
    .A(_008_),
    .B(_038_),
    .Y(_009_)
  );
  NOR _119_ (
    .A(_034_),
    .B(dest),
    .Y(_010_)
  );
  NOR _120_ (
    .A(_010_),
    .B(_009_),
    .Y(_011_)
  );
  NOR _121_ (
    .A(_011_),
    .B(_037_),
    .Y(outdest0[7])
  );
  NOR _122_ (
    .A(dest),
    .B(data_reg1dest[0]),
    .Y(_012_)
  );
  NAND _123_ (
    .A(dest),
    .B(_041_),
    .Y(_013_)
  );
  NAND _124_ (
    .A(_013_),
    .B(reset_L),
    .Y(_014_)
  );
  NOR _125_ (
    .A(_014_),
    .B(_012_),
    .Y(outdest1[0])
  );
  NOR _126_ (
    .A(data_reg1dest[1]),
    .B(dest),
    .Y(_015_)
  );
  NAND _127_ (
    .A(_046_),
    .B(dest),
    .Y(_016_)
  );
  NAND _128_ (
    .A(_016_),
    .B(reset_L),
    .Y(_017_)
  );
  NOR _129_ (
    .A(_017_),
    .B(_015_),
    .Y(outdest1[1])
  );
  NOR _130_ (
    .A(data_reg1dest[2]),
    .B(dest),
    .Y(_018_)
  );
  NAND _131_ (
    .A(_051_),
    .B(dest),
    .Y(_019_)
  );
  NAND _132_ (
    .A(_019_),
    .B(reset_L),
    .Y(_020_)
  );
  NOR _133_ (
    .A(_020_),
    .B(_018_),
    .Y(outdest1[2])
  );
  NOR _134_ (
    .A(data_reg1dest[3]),
    .B(dest),
    .Y(_021_)
  );
  NAND _135_ (
    .A(_056_),
    .B(dest),
    .Y(_022_)
  );
  NAND _136_ (
    .A(_022_),
    .B(reset_L),
    .Y(_023_)
  );
  NOR _137_ (
    .A(_023_),
    .B(_021_),
    .Y(outdest1[3])
  );
  NOR _138_ (
    .A(data_reg1dest[4]),
    .B(dest),
    .Y(_024_)
  );
  NAND _139_ (
    .A(_061_),
    .B(dest),
    .Y(_025_)
  );
  NAND _140_ (
    .A(_025_),
    .B(reset_L),
    .Y(_026_)
  );
  NOR _141_ (
    .A(_026_),
    .B(_024_),
    .Y(outdest1[4])
  );
  NOR _142_ (
    .A(data_reg1dest[5]),
    .B(dest),
    .Y(_027_)
  );
  NAND _143_ (
    .A(_066_),
    .B(dest),
    .Y(_028_)
  );
  NAND _144_ (
    .A(_028_),
    .B(reset_L),
    .Y(_029_)
  );
  NOR _145_ (
    .A(_029_),
    .B(_027_),
    .Y(outdest1[5])
  );
  NOR _146_ (
    .A(data_reg1dest[6]),
    .B(dest),
    .Y(_030_)
  );
  NAND _147_ (
    .A(_005_),
    .B(dest),
    .Y(_031_)
  );
  NAND _148_ (
    .A(_031_),
    .B(reset_L),
    .Y(_032_)
  );
  NOR _149_ (
    .A(_032_),
    .B(_030_),
    .Y(outdest1[6])
  );
  NOR _150_ (
    .A(_036_),
    .B(_033_),
    .Y(_001_[7])
  );
  NOR _151_ (
    .A(_043_),
    .B(_037_),
    .Y(_000_[0])
  );
  NOR _152_ (
    .A(_048_),
    .B(_037_),
    .Y(_000_[1])
  );
  NOR _153_ (
    .A(_053_),
    .B(_037_),
    .Y(_000_[2])
  );
  NOR _154_ (
    .A(_058_),
    .B(_037_),
    .Y(_000_[3])
  );
  NOR _155_ (
    .A(_063_),
    .B(_037_),
    .Y(_000_[4])
  );
  NOR _156_ (
    .A(_002_),
    .B(_037_),
    .Y(_000_[5])
  );
  NOR _157_ (
    .A(_007_),
    .B(_037_),
    .Y(_000_[6])
  );
  NOR _158_ (
    .A(_011_),
    .B(_037_),
    .Y(_000_[7])
  );
  NOR _159_ (
    .A(_014_),
    .B(_012_),
    .Y(_001_[0])
  );
  NOR _160_ (
    .A(_017_),
    .B(_015_),
    .Y(_001_[1])
  );
  NOR _161_ (
    .A(_020_),
    .B(_018_),
    .Y(_001_[2])
  );
  NOR _162_ (
    .A(_023_),
    .B(_021_),
    .Y(_001_[3])
  );
  NOR _163_ (
    .A(_026_),
    .B(_024_),
    .Y(_001_[4])
  );
  NOR _164_ (
    .A(_029_),
    .B(_027_),
    .Y(_001_[5])
  );
  NOR _165_ (
    .A(_032_),
    .B(_030_),
    .Y(_001_[6])
  );
  DFF _166_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_reg0dest[0])
  );
  DFF _167_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_reg0dest[1])
  );
  DFF _168_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_reg0dest[2])
  );
  DFF _169_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_reg0dest[3])
  );
  DFF _170_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_reg0dest[4])
  );
  DFF _171_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_reg0dest[5])
  );
  DFF _172_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_reg0dest[6])
  );
  DFF _173_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_reg0dest[7])
  );
  DFF _174_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_reg1dest[0])
  );
  DFF _175_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_reg1dest[1])
  );
  DFF _176_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_reg1dest[2])
  );
  DFF _177_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_reg1dest[3])
  );
  DFF _178_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_reg1dest[4])
  );
  DFF _179_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_reg1dest[5])
  );
  DFF _180_ (
    .C(clk),
    .D(_001_[6]),
    .Q(data_reg1dest[6])
  );
  DFF _181_ (
    .C(clk),
    .D(_001_[7]),
    .Q(data_reg1dest[7])
  );
endmodule
