/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Mux2a1_dest.v:1" *)
module mux2a1dest_est(pop0, pop1, datain_dest0, datain_dest1, reset_L, validoutdest, dataout_dest);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  (* src = "Mux2a1_dest.v:5" *)
  input [9:0] datain_dest0;
  (* src = "Mux2a1_dest.v:6" *)
  input [9:0] datain_dest1;
  (* src = "Mux2a1_dest.v:10" *)
  output [9:0] dataout_dest;
  (* src = "Mux2a1_dest.v:3" *)
  input pop0;
  (* src = "Mux2a1_dest.v:4" *)
  input pop1;
  (* src = "Mux2a1_dest.v:7" *)
  input reset_L;
  (* src = "Mux2a1_dest.v:9" *)
  output validoutdest;
  NOT _054_ (
    .A(reset_L),
    .Y(_000_)
  );
  NOT _055_ (
    .A(datain_dest1[0]),
    .Y(_001_)
  );
  NOT _056_ (
    .A(pop0),
    .Y(_002_)
  );
  NAND _057_ (
    .A(pop1),
    .B(_002_),
    .Y(_003_)
  );
  NOR _058_ (
    .A(_003_),
    .B(_001_),
    .Y(_004_)
  );
  NOT _059_ (
    .A(datain_dest0[0]),
    .Y(_005_)
  );
  NOR _060_ (
    .A(_005_),
    .B(_002_),
    .Y(_006_)
  );
  NOR _061_ (
    .A(_006_),
    .B(_004_),
    .Y(_007_)
  );
  NOR _062_ (
    .A(_007_),
    .B(_000_),
    .Y(dataout_dest[0])
  );
  NOT _063_ (
    .A(datain_dest1[1]),
    .Y(_008_)
  );
  NOR _064_ (
    .A(_003_),
    .B(_008_),
    .Y(_009_)
  );
  NOT _065_ (
    .A(datain_dest0[1]),
    .Y(_010_)
  );
  NOR _066_ (
    .A(_010_),
    .B(_002_),
    .Y(_011_)
  );
  NOR _067_ (
    .A(_011_),
    .B(_009_),
    .Y(_012_)
  );
  NOR _068_ (
    .A(_012_),
    .B(_000_),
    .Y(dataout_dest[1])
  );
  NOT _069_ (
    .A(datain_dest1[2]),
    .Y(_013_)
  );
  NOR _070_ (
    .A(_003_),
    .B(_013_),
    .Y(_014_)
  );
  NOT _071_ (
    .A(datain_dest0[2]),
    .Y(_015_)
  );
  NOR _072_ (
    .A(_015_),
    .B(_002_),
    .Y(_016_)
  );
  NOR _073_ (
    .A(_016_),
    .B(_014_),
    .Y(_017_)
  );
  NOR _074_ (
    .A(_017_),
    .B(_000_),
    .Y(dataout_dest[2])
  );
  NOT _075_ (
    .A(datain_dest1[3]),
    .Y(_018_)
  );
  NOR _076_ (
    .A(_003_),
    .B(_018_),
    .Y(_019_)
  );
  NOT _077_ (
    .A(datain_dest0[3]),
    .Y(_020_)
  );
  NOR _078_ (
    .A(_020_),
    .B(_002_),
    .Y(_021_)
  );
  NOR _079_ (
    .A(_021_),
    .B(_019_),
    .Y(_022_)
  );
  NOR _080_ (
    .A(_022_),
    .B(_000_),
    .Y(dataout_dest[3])
  );
  NOT _081_ (
    .A(datain_dest1[4]),
    .Y(_023_)
  );
  NOR _082_ (
    .A(_003_),
    .B(_023_),
    .Y(_024_)
  );
  NOT _083_ (
    .A(datain_dest0[4]),
    .Y(_025_)
  );
  NOR _084_ (
    .A(_025_),
    .B(_002_),
    .Y(_026_)
  );
  NOR _085_ (
    .A(_026_),
    .B(_024_),
    .Y(_027_)
  );
  NOR _086_ (
    .A(_027_),
    .B(_000_),
    .Y(dataout_dest[4])
  );
  NOT _087_ (
    .A(datain_dest1[5]),
    .Y(_028_)
  );
  NOR _088_ (
    .A(_003_),
    .B(_028_),
    .Y(_029_)
  );
  NOT _089_ (
    .A(datain_dest0[5]),
    .Y(_030_)
  );
  NOR _090_ (
    .A(_030_),
    .B(_002_),
    .Y(_031_)
  );
  NOR _091_ (
    .A(_031_),
    .B(_029_),
    .Y(_032_)
  );
  NOR _092_ (
    .A(_032_),
    .B(_000_),
    .Y(dataout_dest[5])
  );
  NOT _093_ (
    .A(datain_dest1[6]),
    .Y(_033_)
  );
  NOR _094_ (
    .A(_003_),
    .B(_033_),
    .Y(_034_)
  );
  NOT _095_ (
    .A(datain_dest0[6]),
    .Y(_035_)
  );
  NOR _096_ (
    .A(_035_),
    .B(_002_),
    .Y(_036_)
  );
  NOR _097_ (
    .A(_036_),
    .B(_034_),
    .Y(_037_)
  );
  NOR _098_ (
    .A(_037_),
    .B(_000_),
    .Y(dataout_dest[6])
  );
  NOT _099_ (
    .A(datain_dest1[7]),
    .Y(_038_)
  );
  NOR _100_ (
    .A(_003_),
    .B(_038_),
    .Y(_039_)
  );
  NOT _101_ (
    .A(datain_dest0[7]),
    .Y(_040_)
  );
  NOR _102_ (
    .A(_040_),
    .B(_002_),
    .Y(_041_)
  );
  NOR _103_ (
    .A(_041_),
    .B(_039_),
    .Y(_042_)
  );
  NOR _104_ (
    .A(_042_),
    .B(_000_),
    .Y(dataout_dest[7])
  );
  NOT _105_ (
    .A(datain_dest1[8]),
    .Y(_043_)
  );
  NOR _106_ (
    .A(_003_),
    .B(_043_),
    .Y(_044_)
  );
  NOT _107_ (
    .A(datain_dest0[8]),
    .Y(_045_)
  );
  NOR _108_ (
    .A(_045_),
    .B(_002_),
    .Y(_046_)
  );
  NOR _109_ (
    .A(_046_),
    .B(_044_),
    .Y(_047_)
  );
  NOR _110_ (
    .A(_047_),
    .B(_000_),
    .Y(dataout_dest[8])
  );
  NOT _111_ (
    .A(datain_dest1[9]),
    .Y(_048_)
  );
  NOR _112_ (
    .A(_003_),
    .B(_048_),
    .Y(_049_)
  );
  NOT _113_ (
    .A(datain_dest0[9]),
    .Y(_050_)
  );
  NOR _114_ (
    .A(_050_),
    .B(_002_),
    .Y(_051_)
  );
  NOR _115_ (
    .A(_051_),
    .B(_049_),
    .Y(_052_)
  );
  NOR _116_ (
    .A(_052_),
    .B(_000_),
    .Y(dataout_dest[9])
  );
  NOR _117_ (
    .A(pop1),
    .B(pop0),
    .Y(_053_)
  );
  NOR _118_ (
    .A(_053_),
    .B(_000_),
    .Y(validoutdest)
  );
endmodule
