/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "paraser.v:1" *)
module partoserialEst(data_in, valid_in, reset_L, clk_8f, data_out_P2S);
  (* src = "paraser.v:24" *)
  wire [3:0] _000_;
  (* src = "paraser.v:24" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  (* src = "paraser.v:6" *)
  input clk_8f;
  (* src = "paraser.v:12" *)
  wire [3:0] contador;
  (* src = "paraser.v:3" *)
  input [7:0] data_in;
  (* src = "paraser.v:8" *)
  output data_out_P2S;
  (* src = "paraser.v:5" *)
  input reset_L;
  (* src = "paraser.v:4" *)
  input valid_in;
  NOT _050_ (
    .A(reset_L),
    .Y(_002_)
  );
  NOR _051_ (
    .A(contador[0]),
    .B(_002_),
    .Y(_000_[0])
  );
  NOT _052_ (
    .A(contador[0]),
    .Y(_003_)
  );
  NOT _053_ (
    .A(contador[1]),
    .Y(_004_)
  );
  NOR _054_ (
    .A(_004_),
    .B(_003_),
    .Y(_005_)
  );
  NAND _055_ (
    .A(_004_),
    .B(_003_),
    .Y(_006_)
  );
  NAND _056_ (
    .A(_006_),
    .B(reset_L),
    .Y(_007_)
  );
  NOR _057_ (
    .A(_007_),
    .B(_005_),
    .Y(_000_[1])
  );
  NOR _058_ (
    .A(_005_),
    .B(contador[2]),
    .Y(_008_)
  );
  NAND _059_ (
    .A(_005_),
    .B(contador[2]),
    .Y(_009_)
  );
  NAND _060_ (
    .A(_009_),
    .B(reset_L),
    .Y(_010_)
  );
  NOR _061_ (
    .A(_010_),
    .B(_008_),
    .Y(_000_[2])
  );
  NOT _062_ (
    .A(contador[3]),
    .Y(_011_)
  );
  NOR _063_ (
    .A(_010_),
    .B(_011_),
    .Y(_000_[3])
  );
  NAND _064_ (
    .A(contador[2]),
    .B(_011_),
    .Y(_012_)
  );
  NAND _065_ (
    .A(valid_in),
    .B(reset_L),
    .Y(_013_)
  );
  NOR _066_ (
    .A(_013_),
    .B(data_in[2]),
    .Y(_014_)
  );
  NOR _067_ (
    .A(_014_),
    .B(_012_),
    .Y(_015_)
  );
  NOR _068_ (
    .A(contador[2]),
    .B(contador[3]),
    .Y(_016_)
  );
  NOT _069_ (
    .A(data_in[6]),
    .Y(_017_)
  );
  NOR _070_ (
    .A(_013_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _071_ (
    .A(_018_),
    .B(_016_),
    .Y(_019_)
  );
  NAND _072_ (
    .A(_019_),
    .B(contador[0]),
    .Y(_020_)
  );
  NOR _073_ (
    .A(_020_),
    .B(_015_),
    .Y(_021_)
  );
  NOT _074_ (
    .A(valid_in),
    .Y(_022_)
  );
  NOR _075_ (
    .A(_022_),
    .B(_002_),
    .Y(_023_)
  );
  NOT _076_ (
    .A(contador[2]),
    .Y(_024_)
  );
  NAND _077_ (
    .A(_024_),
    .B(data_in[7]),
    .Y(_025_)
  );
  NAND _078_ (
    .A(_025_),
    .B(_023_),
    .Y(_026_)
  );
  NAND _079_ (
    .A(_026_),
    .B(_011_),
    .Y(_027_)
  );
  NOT _080_ (
    .A(data_in[3]),
    .Y(_028_)
  );
  NOR _081_ (
    .A(_012_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _082_ (
    .A(_029_),
    .B(contador[0]),
    .Y(_030_)
  );
  NAND _083_ (
    .A(_030_),
    .B(_027_),
    .Y(_031_)
  );
  NAND _084_ (
    .A(_031_),
    .B(_004_),
    .Y(_032_)
  );
  NOR _085_ (
    .A(_032_),
    .B(_021_),
    .Y(_033_)
  );
  NOT _086_ (
    .A(data_in[5]),
    .Y(_034_)
  );
  NAND _087_ (
    .A(_023_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _088_ (
    .A(_035_),
    .B(_016_),
    .Y(_036_)
  );
  NOR _089_ (
    .A(_012_),
    .B(_013_),
    .Y(_037_)
  );
  NAND _090_ (
    .A(_037_),
    .B(data_in[1]),
    .Y(_038_)
  );
  NAND _091_ (
    .A(_038_),
    .B(_036_),
    .Y(_039_)
  );
  NOR _092_ (
    .A(_004_),
    .B(contador[0]),
    .Y(_040_)
  );
  NAND _093_ (
    .A(_040_),
    .B(_039_),
    .Y(_041_)
  );
  NOT _094_ (
    .A(data_in[4]),
    .Y(_042_)
  );
  NAND _095_ (
    .A(_023_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _096_ (
    .A(_043_),
    .B(_016_),
    .Y(_044_)
  );
  NAND _097_ (
    .A(_037_),
    .B(data_in[0]),
    .Y(_045_)
  );
  NAND _098_ (
    .A(_045_),
    .B(_044_),
    .Y(_046_)
  );
  NAND _099_ (
    .A(_046_),
    .B(_005_),
    .Y(_047_)
  );
  NAND _100_ (
    .A(_047_),
    .B(_041_),
    .Y(_048_)
  );
  NOR _101_ (
    .A(_048_),
    .B(_033_),
    .Y(_049_)
  );
  NOR _102_ (
    .A(_049_),
    .B(_002_),
    .Y(_001_)
  );
  DFF _103_ (
    .C(clk_8f),
    .D(_001_),
    .Q(data_out_P2S)
  );
  DFF _104_ (
    .C(clk_8f),
    .D(_000_[0]),
    .Q(contador[0])
  );
  DFF _105_ (
    .C(clk_8f),
    .D(_000_[1]),
    .Q(contador[1])
  );
  DFF _106_ (
    .C(clk_8f),
    .D(_000_[2]),
    .Q(contador[2])
  );
  DFF _107_ (
    .C(clk_8f),
    .D(_000_[3]),
    .Q(contador[3])
  );
endmodule

(* top =  1  *)
(* src = "serializacionEst.v:2" *)
module serializacionEst(data_in0, data_in1, valid_in0, valid_in1, reset_L, clk_8f, data_out_P2S0, data_out_P2S1);
  (* src = "serializacionEst.v:9" *)
  input clk_8f;
  (* src = "serializacionEst.v:4" *)
  input [7:0] data_in0;
  (* src = "serializacionEst.v:5" *)
  input [7:0] data_in1;
  (* src = "serializacionEst.v:11" *)
  output data_out_P2S0;
  (* src = "serializacionEst.v:12" *)
  output data_out_P2S1;
  (* src = "serializacionEst.v:8" *)
  input reset_L;
  (* src = "serializacionEst.v:6" *)
  input valid_in0;
  (* src = "serializacionEst.v:7" *)
  input valid_in1;
  (* src = "serializacionEst.v:14" *)
  partoserialEst p2s0 (
    .clk_8f(clk_8f),
    .data_in(data_in0),
    .data_out_P2S(data_out_P2S0),
    .reset_L(reset_L),
    .valid_in(valid_in0)
  );
  (* src = "serializacionEst.v:15" *)
  partoserialEst p2s1 (
    .clk_8f(clk_8f),
    .data_in(data_in1),
    .data_out_P2S(data_out_P2S1),
    .reset_L(reset_L),
    .valid_in(valid_in1)
  );
endmodule
