/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "Demux1a2_class.v:1" *)
module demux1a2class_est(datain_class, class, dest, reset_L, clk, outclass0, outclass1);
  (* src = "Demux1a2_class.v:35" *)
  wire [9:0] _000_;
  (* src = "Demux1a2_class.v:35" *)
  wire [9:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  (* src = "Demux1a2_class.v:4" *)
  input class;
  (* src = "Demux1a2_class.v:7" *)
  input clk;
  (* src = "Demux1a2_class.v:12" *)
  wire [9:0] data_reg0;
  (* src = "Demux1a2_class.v:12" *)
  wire [9:0] data_reg1;
  (* src = "Demux1a2_class.v:3" *)
  input [7:0] datain_class;
  (* src = "Demux1a2_class.v:5" *)
  input dest;
  (* src = "Demux1a2_class.v:9" *)
  output [9:0] outclass0;
  (* src = "Demux1a2_class.v:10" *)
  output [9:0] outclass1;
  (* src = "Demux1a2_class.v:6" *)
  input reset_L;
  NOR _078_ (
    .A(data_reg1[1]),
    .B(class),
    .Y(_055_)
  );
  NOT _079_ (
    .A(datain_class[1]),
    .Y(_056_)
  );
  NAND _080_ (
    .A(_056_),
    .B(class),
    .Y(_057_)
  );
  NAND _081_ (
    .A(_057_),
    .B(reset_L),
    .Y(_058_)
  );
  NOR _082_ (
    .A(_058_),
    .B(_055_),
    .Y(outclass1[1])
  );
  NOR _083_ (
    .A(data_reg1[2]),
    .B(class),
    .Y(_059_)
  );
  NOT _084_ (
    .A(datain_class[2]),
    .Y(_060_)
  );
  NAND _085_ (
    .A(_060_),
    .B(class),
    .Y(_061_)
  );
  NAND _086_ (
    .A(_061_),
    .B(reset_L),
    .Y(_062_)
  );
  NOR _087_ (
    .A(_062_),
    .B(_059_),
    .Y(outclass1[2])
  );
  NOR _088_ (
    .A(data_reg1[3]),
    .B(class),
    .Y(_063_)
  );
  NOT _089_ (
    .A(datain_class[3]),
    .Y(_064_)
  );
  NAND _090_ (
    .A(_064_),
    .B(class),
    .Y(_065_)
  );
  NAND _091_ (
    .A(_065_),
    .B(reset_L),
    .Y(_066_)
  );
  NOR _092_ (
    .A(_066_),
    .B(_063_),
    .Y(outclass1[3])
  );
  NOR _093_ (
    .A(data_reg1[4]),
    .B(class),
    .Y(_067_)
  );
  NOT _094_ (
    .A(datain_class[4]),
    .Y(_068_)
  );
  NAND _095_ (
    .A(_068_),
    .B(class),
    .Y(_069_)
  );
  NAND _096_ (
    .A(_069_),
    .B(reset_L),
    .Y(_070_)
  );
  NOR _097_ (
    .A(_070_),
    .B(_067_),
    .Y(outclass1[4])
  );
  NOR _098_ (
    .A(data_reg1[5]),
    .B(class),
    .Y(_071_)
  );
  NOT _099_ (
    .A(datain_class[5]),
    .Y(_072_)
  );
  NAND _100_ (
    .A(_072_),
    .B(class),
    .Y(_073_)
  );
  NAND _101_ (
    .A(_073_),
    .B(reset_L),
    .Y(_074_)
  );
  NOR _102_ (
    .A(_074_),
    .B(_071_),
    .Y(outclass1[5])
  );
  NOR _103_ (
    .A(data_reg1[6]),
    .B(class),
    .Y(_075_)
  );
  NOT _104_ (
    .A(datain_class[6]),
    .Y(_076_)
  );
  NAND _105_ (
    .A(_076_),
    .B(class),
    .Y(_077_)
  );
  NAND _106_ (
    .A(_077_),
    .B(reset_L),
    .Y(_002_)
  );
  NOR _107_ (
    .A(_002_),
    .B(_075_),
    .Y(outclass1[6])
  );
  NOR _108_ (
    .A(data_reg1[7]),
    .B(class),
    .Y(_003_)
  );
  NOT _109_ (
    .A(datain_class[7]),
    .Y(_004_)
  );
  NAND _110_ (
    .A(_004_),
    .B(class),
    .Y(_005_)
  );
  NAND _111_ (
    .A(_005_),
    .B(reset_L),
    .Y(_006_)
  );
  NOR _112_ (
    .A(_006_),
    .B(_003_),
    .Y(outclass1[7])
  );
  NOR _113_ (
    .A(data_reg1[8]),
    .B(class),
    .Y(_007_)
  );
  NOT _114_ (
    .A(dest),
    .Y(_008_)
  );
  NAND _115_ (
    .A(_008_),
    .B(class),
    .Y(_009_)
  );
  NAND _116_ (
    .A(_009_),
    .B(reset_L),
    .Y(_010_)
  );
  NOR _117_ (
    .A(_010_),
    .B(_007_),
    .Y(outclass1[8])
  );
  NOT _118_ (
    .A(reset_L),
    .Y(_011_)
  );
  NOR _119_ (
    .A(data_reg1[9]),
    .B(class),
    .Y(_012_)
  );
  NOR _120_ (
    .A(_012_),
    .B(_011_),
    .Y(outclass1[9])
  );
  NOT _121_ (
    .A(class),
    .Y(_013_)
  );
  NOT _122_ (
    .A(data_reg0[0]),
    .Y(_014_)
  );
  NOR _123_ (
    .A(_014_),
    .B(_013_),
    .Y(_015_)
  );
  NOT _124_ (
    .A(datain_class[0]),
    .Y(_016_)
  );
  NOR _125_ (
    .A(_016_),
    .B(class),
    .Y(_017_)
  );
  NOR _126_ (
    .A(_017_),
    .B(_015_),
    .Y(_018_)
  );
  NOR _127_ (
    .A(_018_),
    .B(_011_),
    .Y(outclass0[0])
  );
  NOT _128_ (
    .A(data_reg0[1]),
    .Y(_019_)
  );
  NOR _129_ (
    .A(_019_),
    .B(_013_),
    .Y(_020_)
  );
  NOR _130_ (
    .A(_056_),
    .B(class),
    .Y(_021_)
  );
  NOR _131_ (
    .A(_021_),
    .B(_020_),
    .Y(_022_)
  );
  NOR _132_ (
    .A(_022_),
    .B(_011_),
    .Y(outclass0[1])
  );
  NOT _133_ (
    .A(data_reg0[2]),
    .Y(_023_)
  );
  NOR _134_ (
    .A(_023_),
    .B(_013_),
    .Y(_024_)
  );
  NOR _135_ (
    .A(_060_),
    .B(class),
    .Y(_025_)
  );
  NOR _136_ (
    .A(_025_),
    .B(_024_),
    .Y(_026_)
  );
  NOR _137_ (
    .A(_026_),
    .B(_011_),
    .Y(outclass0[2])
  );
  NOT _138_ (
    .A(data_reg0[3]),
    .Y(_027_)
  );
  NOR _139_ (
    .A(_027_),
    .B(_013_),
    .Y(_028_)
  );
  NOR _140_ (
    .A(_064_),
    .B(class),
    .Y(_029_)
  );
  NOR _141_ (
    .A(_029_),
    .B(_028_),
    .Y(_030_)
  );
  NOR _142_ (
    .A(_030_),
    .B(_011_),
    .Y(outclass0[3])
  );
  NOT _143_ (
    .A(data_reg0[4]),
    .Y(_031_)
  );
  NOR _144_ (
    .A(_031_),
    .B(_013_),
    .Y(_032_)
  );
  NOR _145_ (
    .A(_068_),
    .B(class),
    .Y(_033_)
  );
  NOR _146_ (
    .A(_033_),
    .B(_032_),
    .Y(_034_)
  );
  NOR _147_ (
    .A(_034_),
    .B(_011_),
    .Y(outclass0[4])
  );
  NOT _148_ (
    .A(data_reg0[5]),
    .Y(_035_)
  );
  NOR _149_ (
    .A(_035_),
    .B(_013_),
    .Y(_036_)
  );
  NOR _150_ (
    .A(_072_),
    .B(class),
    .Y(_037_)
  );
  NOR _151_ (
    .A(_037_),
    .B(_036_),
    .Y(_038_)
  );
  NOR _152_ (
    .A(_038_),
    .B(_011_),
    .Y(outclass0[5])
  );
  NOT _153_ (
    .A(data_reg0[6]),
    .Y(_039_)
  );
  NOR _154_ (
    .A(_039_),
    .B(_013_),
    .Y(_040_)
  );
  NOR _155_ (
    .A(_076_),
    .B(class),
    .Y(_041_)
  );
  NOR _156_ (
    .A(_041_),
    .B(_040_),
    .Y(_042_)
  );
  NOR _157_ (
    .A(_042_),
    .B(_011_),
    .Y(outclass0[6])
  );
  NOT _158_ (
    .A(data_reg0[7]),
    .Y(_043_)
  );
  NOR _159_ (
    .A(_043_),
    .B(_013_),
    .Y(_044_)
  );
  NOR _160_ (
    .A(_004_),
    .B(class),
    .Y(_045_)
  );
  NOR _161_ (
    .A(_045_),
    .B(_044_),
    .Y(_046_)
  );
  NOR _162_ (
    .A(_046_),
    .B(_011_),
    .Y(outclass0[7])
  );
  NOT _163_ (
    .A(data_reg0[8]),
    .Y(_047_)
  );
  NOR _164_ (
    .A(_047_),
    .B(_013_),
    .Y(_048_)
  );
  NOR _165_ (
    .A(_008_),
    .B(class),
    .Y(_049_)
  );
  NOR _166_ (
    .A(_049_),
    .B(_048_),
    .Y(_050_)
  );
  NOR _167_ (
    .A(_050_),
    .B(_011_),
    .Y(outclass0[8])
  );
  NAND _168_ (
    .A(data_reg0[9]),
    .B(reset_L),
    .Y(_051_)
  );
  NOR _169_ (
    .A(_051_),
    .B(_013_),
    .Y(outclass0[9])
  );
  NOR _170_ (
    .A(data_reg1[0]),
    .B(class),
    .Y(_052_)
  );
  NAND _171_ (
    .A(_016_),
    .B(class),
    .Y(_053_)
  );
  NAND _172_ (
    .A(_053_),
    .B(reset_L),
    .Y(_054_)
  );
  NOR _173_ (
    .A(_054_),
    .B(_052_),
    .Y(outclass1[0])
  );
  NOR _174_ (
    .A(_058_),
    .B(_055_),
    .Y(_001_[1])
  );
  NOR _175_ (
    .A(_062_),
    .B(_059_),
    .Y(_001_[2])
  );
  NOR _176_ (
    .A(_066_),
    .B(_063_),
    .Y(_001_[3])
  );
  NOR _177_ (
    .A(_070_),
    .B(_067_),
    .Y(_001_[4])
  );
  NOR _178_ (
    .A(_074_),
    .B(_071_),
    .Y(_001_[5])
  );
  NOR _179_ (
    .A(_002_),
    .B(_075_),
    .Y(_001_[6])
  );
  NOR _180_ (
    .A(_006_),
    .B(_003_),
    .Y(_001_[7])
  );
  NOR _181_ (
    .A(_010_),
    .B(_007_),
    .Y(_001_[8])
  );
  NOR _182_ (
    .A(_012_),
    .B(_011_),
    .Y(_001_[9])
  );
  NOR _183_ (
    .A(_018_),
    .B(_011_),
    .Y(_000_[0])
  );
  NOR _184_ (
    .A(_022_),
    .B(_011_),
    .Y(_000_[1])
  );
  NOR _185_ (
    .A(_026_),
    .B(_011_),
    .Y(_000_[2])
  );
  NOR _186_ (
    .A(_030_),
    .B(_011_),
    .Y(_000_[3])
  );
  NOR _187_ (
    .A(_034_),
    .B(_011_),
    .Y(_000_[4])
  );
  NOR _188_ (
    .A(_038_),
    .B(_011_),
    .Y(_000_[5])
  );
  NOR _189_ (
    .A(_042_),
    .B(_011_),
    .Y(_000_[6])
  );
  NOR _190_ (
    .A(_046_),
    .B(_011_),
    .Y(_000_[7])
  );
  NOR _191_ (
    .A(_050_),
    .B(_011_),
    .Y(_000_[8])
  );
  NOR _192_ (
    .A(_051_),
    .B(_013_),
    .Y(_000_[9])
  );
  NOR _193_ (
    .A(_054_),
    .B(_052_),
    .Y(_001_[0])
  );
  DFF _194_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_reg0[0])
  );
  DFF _195_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_reg0[1])
  );
  DFF _196_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_reg0[2])
  );
  DFF _197_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_reg0[3])
  );
  DFF _198_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_reg0[4])
  );
  DFF _199_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_reg0[5])
  );
  DFF _200_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_reg0[6])
  );
  DFF _201_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_reg0[7])
  );
  DFF _202_ (
    .C(clk),
    .D(_000_[8]),
    .Q(data_reg0[8])
  );
  DFF _203_ (
    .C(clk),
    .D(_000_[9]),
    .Q(data_reg0[9])
  );
  DFF _204_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_reg1[0])
  );
  DFF _205_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_reg1[1])
  );
  DFF _206_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_reg1[2])
  );
  DFF _207_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_reg1[3])
  );
  DFF _208_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_reg1[4])
  );
  DFF _209_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_reg1[5])
  );
  DFF _210_ (
    .C(clk),
    .D(_001_[6]),
    .Q(data_reg1[6])
  );
  DFF _211_ (
    .C(clk),
    .D(_001_[7]),
    .Q(data_reg1[7])
  );
  DFF _212_ (
    .C(clk),
    .D(_001_[8]),
    .Q(data_reg1[8])
  );
  DFF _213_ (
    .C(clk),
    .D(_001_[9]),
    .Q(data_reg1[9])
  );
endmodule
